### ISSUE TITLE
App SDK issue: for loops without JSON variables not looping

### ISSUE THREAD

**Issue by AndreAzzalin** [frikky/Shuffle-apps#16]
Hello,

First of all great work frikky :)

Im trying this tools for integraton with theHive, at this moment I created worflows with these nodes:

https://pasteboard.co/JrFvpTLe.png

- getObservables: getting observables from case
- getIpAnalyzers: getting avaible analyzers for IP
- getDomainAnalyzers:  getting avaible analyzers for domain
- runAnalyzers: run analyzers for $getObervables.#.id

"run analyzers" function of TheHive app works with single artifact_id but it dosen't work with multiple artifacts like array of artifact_id ( $getObservables.#.id)

Best regards
A.A.

**Comment by frikky** [comment]
Hey @AndreAzzalin and thanks! 

Can you share the (redacted) data returned from getObservables? 
Also: there was a bug with loops and JSON that was fixed two days ago. Have you recreated the app after that (Force update from Github)?

**Comment by AndreAzzalin** [comment]
Hello,

Thanks for reply, here the JSON returned from getObservables:

"Results for getObservables":[4 items
 0:{18 items
"_routing":"AXN8RSAvZP8HpukK-_R_"
"reports":{}0 items
"data":"91.189.88.152"
"dataType":"ip"
"_type":"case_artifact"
"sighted":false
"message":"Found in the email body"
"tags":[...]1 item
"createdAt":1595517778023
"_parent":"AXN8RSAvZP8HpukK-_R_"
"createdBy":"synapse"
"tlp":2
"_id":"bd0da20b7fa79e1cd1f26b69a024bebe"
"id":"bd0da20b7fa79e1cd1f26b69a024bebe"
"ioc":false
"_version":1
"startDate":1595517778024
"status":"Ok"
}
1:{...}20 items 
2:{...}20 items 
]

I've already force update from your repo but it still doesn't work, runAnalyzer return :

> Status FAILURE
> Result General exception: list index out of range

Parameters pass to runAnalyzer function :

> analyzer_id: 
> $getIpAnalyzers.#
> 
> artifact_id:
> $getObservables.#._id

Hopefully you have all the information you need while I'm working on the script to make it work 

Regards :)

**Comment by frikky** [comment]
Well, good thing is you've understood how the system works, bad thing is that there seems to be an issue with the system itself. In my PoC with that data it worked, so I have one more check before I'll properly test it with TheHive myself:

* Did you update the App SDK before force updating? It can be done like this:
```
docker pull frikky/shuffle:app_sdk
```

I totally forgot about that bit in my last message. This also reminds me that I should have a frontend check for that sort of stuff.

**Comment by AndreAzzalin** [comment]
I've force updating with:

` docker pull frikky/shuffle:app_sdk`

only after the docker restart the changes were effective, but now function runAnayzer return different error :

**PARAMETERS:**

**analyzer_id:** $getIpAnalyzers.#


> Status SUCCESS
> Result ['GoogleSafebrowsing_2_0', 'VirusTotal_GetReport_3_0', 'URLhaus_2_0', 'MISP_2_1', 'OTXQuery_2_0', 'GoogleDNS_resolve_1_0_0', 'Abuse_Finder_3_0', 'Threatcrowd_1_0', 'CyberCrime-Tracker_1_0', 'Mnemonic_pDNS_Public_3_0', 'Urlscan_io_Scan_0_1_0']

**artifact_id:** $getObservables.#.id

> "Results for getObservables":[4 items
> 0:{18 items
> "_routing":"AXS2jJ0UaSCDULf45fwq"
> "reports":{}0 items
> "data":"90.147.160.70"
> "dataType":"ip"
> "_type":"case_artifact"
> "sighted":false
> "message":"Found in the email body"
> "tags":[...]1 item
> "createdAt":1600790509008
> "_parent":"AXS2jJ0UaSCDULf45fwq"
> "createdBy":"synapse"
> "tlp":2
> "_id":"da39832a62b5186912ac5db67ffff126"
> "id":"da39832a62b5186912ac5db67ffff126"
> "ioc":false
> "_version":1
> "startDate":1600790509009
> "status":"Ok"
> }
> 1:{...}18 items
> 2:{...}18 items
> 3:{...}18 items
> ]

**RETURN VALUE:**

> "Results for runAnalyzer":{2 items
> "type":"NotFoundError"
> "message":"analyzer ["DShield_lookup_1_0", "GreyNoise_2_3", "VirusTotal_GetReport_3_0", "URLhaus_2_0", "MISP_2_1", "AbuseIPDB_1_0", "OTXQuery_2_0", "GoogleDNS_resolve_1_0_0", "Abuse_Finder_3_0", "TalosReputation_1_0", "Threatcrowd_1_0", "CyberCrime-Tracker_1_0", "Mnemonic_pDNS_Public_3_0"] not found"
> }

I don't understand if I'm missing something :(

**Comment by frikky** [comment]
Looks like it's sending all the values rather than looping them, which is incorrect behavior from the App SDK. You're doing it exactly right :D 
I'll get it fixed within the week :)

PS: You're one of the first to try using loops properly after I did the last fix, which is why it's kind of wonky. Sorry about the issues.

**Comment by AndreAzzalin** [comment]
lol no problem
Thanks for your kind support, it's a pleasure for me helping you improve this project 👍

**Comment by frikky** [comment]
Heyo! 

Try to update your App_sdk, then run force update again! This issues should now be fixed :fire: 
```
# Updating:
docker pull frikky/shuffle:app_sdk
```

**Comment by AndreAzzalin** [comment]
Hey Frikky,

Unfortunately still doesn't work, also after force pull from docker :(
for function runAnalyzer return:

```
Status FAILURE
Result General exception: list index out of range
```

Are you sure to push new fixed code for TheHive app? :)

**Comment by frikky** [comment]
Alright, I'll set it up properly myself and test! I'll get back to you - this shouldn't be an issue :disappointed:

**Comment by frikky** [comment]
I pushed yet another fix to loops in the app SDK, and tested a lot with your data meaning: it _should_ work now.
Can you run the updating process again and try?

1:
```
docker pull frikky/shuffle:app_sdk
```

2: Click "force update" on the apps

**Comment by frikky** [comment]
Update again: I did a major update to the app SDK today to fix this issue. Please update it and tell me how it works :+1:

**Comment by AndreAzzalin** [comment]
I also update here the status of the issue

Im follow the pull procedure:

1. docker pull frikky/shuffle:app_sdk
2. wait some minute 
3. "force update" on the apps 

Unfortunally app with function "runAnalyzer" still return:

```
Status FAILURE
Result General exception: list index out of range
```

**Comment by frikky** [comment]
Working on it. This is a tricky issue and is also hard to test :/

**Comment by frikky** [comment]
Fixed and verified by @AndreAzzalin in an email. 

Reference ID: https://github.com/frikky/Shuffle/commit/722d832d881de4bfeafc2424d8145c37f779002c

PS: This issue will kind of show up again when we reach >2 loops. 
Reference issue: https://github.com/frikky/Shuffle/issues/170
